# Site Settings
title: "ALSKai的个人网站"
title_separator: "|"
subtitle: "AI时代的工具驯服师"
name: "ALSKai"
description: "产品经理 | AI工具实践者 | 跨界创新者 - 让复杂工具变成效率倍增器"
url: "https://albert-lsk.github.io" # 你的GitHub Pages URL
baseurl: "" # 如果部署在子目录,填写如 "/blog"
repository: "Albert-Lsk/Albert-Lsk.github.io" # GitHub用户名/仓库名
teaser: "/assets/images/teaser-default.jpg"
logo: "/assets/images/logo.png"
masthead_title: "ALSKai"
breadcrumbs: true
words_per_minute: 200

# SEO优化
locale: "zh-CN"
timezone: Asia/Shanghai

# 评论系统 (可选,暂时禁用)
comments:
  provider: false

# 搜索
search: true
search_full_content: true
search_provider: lunr

# Analytics (可选)
analytics:
  provider: false

# 作者信息
author:
  name: "ALSKai"
  avatar: "/assets/images/avatar.jpg"
  bio: "AI时代的工具驯服师<br>产品经理 | 前船舶工程师<br>让复杂工具变成效率倍增器"
  location: "中国"
  email: "carlalbert9596@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Albert-Lsk"
    - label: "CSDN博客"
      icon: "fas fa-fw fa-blog"
      url: "https://blog.csdn.net/AlbertDS"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:carlalbert9596@gmail.com"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Albert-Lsk"
    - label: "CSDN"
      icon: "fas fa-fw fa-blog"
      url: "https://blog.csdn.net/AlbertDS"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/
timezone: Asia/Shanghai

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_label: "目录"
      toc_icon: "list"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

# 如果使用远程主题(推荐GitHub Pages)
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# 注意:使用remote_theme时需要注释掉上面的theme行